# Generated by Django 3.0.5 on 2020-06-20 13:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Books&Sports', 'Books&Sports'), ('Others', 'Others'), ('Furniture', 'Furniture'), ('Bicycle', 'Bicycle'), ('Electronics', 'Electronics'), ('Mobiles', 'Mobiles'), ('Fashion', 'Fashion')], max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], max_length=100)),
                ('College', models.CharField(choices=[('IITG', 'IIT Guwahati'), ('IITP', 'IIT Patna'), ('IIT(ISM)', 'IIT (ISM) Dhanbad'), ('IITMandi', 'IIT Mandi'), ('IITGoa', 'IIT Goa'), ('IITGN', 'IIT Gandhinagar'), ('IITDH', 'IIT Dharwad'), ('IITD', 'IIT Delhi'), ('IITR', 'IIT Roorkee'), ('IITPKD', 'IIT Palakkad'), ('IITTP', 'IIT Tirupati'), ('IITB', 'IIT Bombay'), ('IITK', 'IIT Kanpur'), ('IITJMU', 'IIT Jammu'), ('IITM', 'IIT Madras'), ('IITBBS', 'IIT Bhubaneswar'), ('IITH', 'IIT Hyderabad'), ('IITKGP', 'IIT kharagpur'), ('IITRPR', 'IIT Ropar'), ('IITI', 'IIT Indore'), ('IIT (BHU)', 'IIT (BHU) Varanasi'), ('IITBH', 'IIT Bhilai'), ('IITJ', 'IIT Jodhpur')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateField(default=datetime.datetime.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
