# Generated by Django 3.0.7 on 2020-06-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200621_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='College',
            field=models.CharField(choices=[('IITP', 'IIT Patna'), ('IITGN', 'IIT Gandhinagar'), ('IITKGP', 'IIT kharagpur'), ('IITJ', 'IIT Jodhpur'), ('IITBBS', 'IIT Bhubaneswar'), ('IITM', 'IIT Madras'), ('IITRPR', 'IIT Ropar'), ('IITK', 'IIT Kanpur'), ('IIT(ISM)', 'IIT (ISM) Dhanbad'), ('IITB', 'IIT Bombay'), ('IITR', 'IIT Roorkee'), ('IITPKD', 'IIT Palakkad'), ('IITI', 'IIT Indore'), ('IITDH', 'IIT Dharwad'), ('IIT (BHU)', 'IIT (BHU) Varanasi'), ('IITJMU', 'IIT Jammu'), ('IITBH', 'IIT Bhilai'), ('IITMandi', 'IIT Mandi'), ('IITGoa', 'IIT Goa'), ('IITG', 'IIT Guwahati'), ('IITH', 'IIT Hyderabad'), ('IITD', 'IIT Delhi'), ('IITTP', 'IIT Tirupati')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Mobiles', 'Mobiles'), ('Others', 'Others'), ('Bicycle', 'Bicycle'), ('Books&Sports', 'Books&Sports')], max_length=100),
        ),
    ]
