# Generated by Django 3.0.7 on 2020-06-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20200621_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='College',
            field=models.CharField(choices=[('IITB', 'IIT Bombay'), ('IITI', 'IIT Indore'), ('IITG', 'IIT Guwahati'), ('IITH', 'IIT Hyderabad'), ('IITDH', 'IIT Dharwad'), ('IITTP', 'IIT Tirupati'), ('IIT (BHU)', 'IIT (BHU) Varanasi'), ('IITMandi', 'IIT Mandi'), ('IITJ', 'IIT Jodhpur'), ('IITJMU', 'IIT Jammu'), ('IITP', 'IIT Patna'), ('IITK', 'IIT Kanpur'), ('IITPKD', 'IIT Palakkad'), ('IITKGP', 'IIT kharagpur'), ('IITM', 'IIT Madras'), ('IITGoa', 'IIT Goa'), ('IIT(ISM)', 'IIT (ISM) Dhanbad'), ('IITRPR', 'IIT Ropar'), ('IITBBS', 'IIT Bhubaneswar'), ('IITD', 'IIT Delhi'), ('IITBH', 'IIT Bhilai'), ('IITR', 'IIT Roorkee'), ('IITGN', 'IIT Gandhinagar')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Bicycle', 'Bicycle'), ('Mobiles', 'Mobiles'), ('Fashion', 'Fashion'), ('Books&Sports', 'Books&Sports'), ('Electronics', 'Electronics'), ('Others', 'Others'), ('Furniture', 'Furniture')], max_length=100),
        ),
    ]
